import React, { useEffect, useRef, useState } from 'react';
import {
  FlatList,
  GestureResponderEvent,
  Image,
  KeyboardAvoidingView,
  ListRenderItemInfo,
  Modal,
  PanResponder,
  PanResponderGestureState,
  Platform,
  SafeAreaView,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import { Href, useLocalSearchParams, useRouter } from 'expo-router';
import DraggableFlatList, { RenderItemParams, ScaleDecorator } from 'react-native-draggable-flatlist';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import { Colors } from '@/constants/colors';
import { supabase } from '@/lib/supabase';
import { confirm, notify } from '@/lib/confirm';
import { USE_MOCK } from '@/lib/env';
import { MOCK_WORKOUT } from '@/mocks/workout';
import { WorkoutMovement } from '@/types';

// react-native-draggable-flatlist's long-press-drag gesture relies on native
// view measurement that doesn't work reliably in React Native Web — the drag
// visually "picks up" the row but never commits a reorder (verified directly).
// On web we drive the same mouse-drag-a-row interaction with plain
// PanResponder instead, which react-native-web implements on top of regular
// mouse events and does work.
const IS_WEB = Platform.OS === 'web';
const ROW_PITCH_FALLBACK = 90; // card height + list gap, refined by onLayout below
const DEFAULT_REST_SEC = 3;

interface ReviewMovement extends WorkoutMovement {
  _key: string; // stable key even after duplicating
}

interface EditTarget {
  type: 'title' | 'movement-name' | 'movement-duration' | 'all-move-durations' | 'all-rest-durations';
  key: string;
  movementId?: string;
  current: string;
}

// A brand-new movement row (no existing DB id to reuse, unlike duplicate()
// which points at an existing one) — saveEdits inserts these instead of
// updating.
function makeRestMovement(sourceVideoId: string, durationSec: number, autoGenerated: boolean): ReviewMovement['movement'] {
  return {
    id: `new_movement_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
    source_video_id: sourceVideoId,
    position: 0,
    name: 'Rest',
    mode: 'timed',
    start_sec: null,
    end_sec: null,
    duration_sec: durationSec,
    reps: null,
    sets: null,
    clip_url: null,
    thumbnail_url: null,
    detection_method: 'manual',
    confidence: 1,
    is_rest: true,
    auto_generated: autoGenerated,
    created_at: new Date().toISOString(),
  };
}

export default function ReviewScreen() {
  const { id, new: isNew } = useLocalSearchParams<{ id: string; new?: string }>();
  const router = useRouter();

  const [title, setTitle] = useState('');
  const [sourceVideoId, setSourceVideoId] = useState<string>('');
  const [movements, setMovements] = useState<ReviewMovement[]>([]);
  const [restOn, setRestOn] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [editTarget, setEditTarget] = useState<EditTarget | null>(null);
  const [editValue, setEditValue] = useState('');

  // Web-only mouse drag-to-reorder state.
  const [webDragKey, setWebDragKey] = useState<string | null>(null);
  const [webDragY, setWebDragY] = useState(0);
  const webDragStartIndex = useRef(0);
  const webRowPitch = useRef(ROW_PITCH_FALLBACK);
  // Dragging calls setMovements/setWebDragY on every mousemove, which
  // re-renders every row — without caching, that rebuilds a PanResponder
  // (and all its gesture closures) for every row on every single frame of
  // a drag. Cached per row key instead, built once and reused; the ref
  // below keeps onPanResponderGrant reading the current movements array
  // without needing the responder to be rebuilt when it changes.
  const movementsRef = useRef<ReviewMovement[]>([]);
  movementsRef.current = movements;
  const webPanResponders = useRef(new Map<string, ReturnType<typeof PanResponder.create>>());

  useEffect(() => {
    if (!id) return;

    if (USE_MOCK && id === MOCK_WORKOUT.id) {
      const initial = (MOCK_WORKOUT.movements ?? []).map((m) => ({ ...m, _key: m.id }));
      setTitle(MOCK_WORKOUT.title);
      setSourceVideoId(MOCK_WORKOUT.source_video_id);
      setMovements(initial);
      setRestOn(initial.some((m) => m.movement.auto_generated));
      setLoading(false);
      return;
    }

    supabase
      .from('workouts')
      .select(`
        title,
        source_video_id,
        movements:workout_movements(
          *,
          movement:movements(*)
        )
      `)
      .eq('id', id)
      .order('position', { referencedTable: 'workout_movements' })
      .single()
      .then(({ data, error }) => {
        if (error || !data) return;
        const initial = (data.movements ?? []).map((m: WorkoutMovement) => ({ ...m, _key: m.id }));
        setTitle(data.title);
        setSourceVideoId(data.source_video_id);
        setMovements(initial);
        setRestOn(initial.some((m) => m.movement.auto_generated));
        setLoading(false);
      });
  }, [id]);

  const openEdit = (target: EditTarget) => {
    setEditTarget(target);
    setEditValue(target.current);
  };

  const commitEdit = () => {
    if (!editTarget) return;
    const val = editValue.trim();
    if (!val) { setEditTarget(null); return; }

    if (editTarget.type === 'title') {
      setTitle(val);
    } else if (editTarget.type === 'movement-name') {
      setMovements((prev) =>
        prev.map((m) =>
          m._key === editTarget.key
            ? { ...m, movement: { ...m.movement, name: val } }
            : m
        )
      );
    } else if (editTarget.type === 'movement-duration') {
      const secs = Math.max(1, parseInt(val, 10) || 0);
      setMovements((prev) =>
        prev.map((m) =>
          m._key === editTarget.key
            ? { ...m, movement: { ...m.movement, duration_sec: secs } }
            : m
        )
      );
    } else if (editTarget.type === 'all-move-durations') {
      const secs = Math.max(1, parseInt(val, 10) || 0);
      setMovements((prev) =>
        prev.map((m) => (m.movement.is_rest ? m : { ...m, movement: { ...m.movement, duration_sec: secs } }))
      );
    } else if (editTarget.type === 'all-rest-durations') {
      const secs = Math.max(1, parseInt(val, 10) || 0);
      setMovements((prev) =>
        prev.map((m) => (m.movement.is_rest ? { ...m, movement: { ...m.movement, duration_sec: secs } } : m))
      );
    }
    setEditTarget(null);
  };

  const duplicate = (key: string) => {
    setMovements((prev) => {
      const idx = prev.findIndex((m) => m._key === key);
      if (idx === -1) return prev;
      const original = prev[idx];
      // A genuinely independent copy — sharing the original's movement.id
      // (as a plain spread would) means editing either one's duration and
      // saving overwrites the same DB row, and inheriting auto_generated
      // means the "rest between moves" toggle can delete this copy along
      // with the real auto-generated rests it's meant to leave alone.
      const newMovementId = `new_movement_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
      const copy: ReviewMovement = {
        ...original,
        _key: `${original._key}_copy_${Date.now()}`,
        id: `new_${Date.now()}`,
        movement_id: newMovementId,
        movement: {
          ...original.movement,
          id: newMovementId,
          auto_generated: false,
          created_at: new Date().toISOString(),
        },
      };
      const next = [...prev];
      next.splice(idx + 1, 0, copy);
      return next;
    });
  };

  // Adds a rest by hand, independent of the global toggle — auto_generated
  // stays false, so the toggle never removes it.
  const insertRestAfter = (key: string) => {
    setMovements((prev) => {
      const idx = prev.findIndex((m) => m._key === key);
      if (idx === -1) return prev;
      const movement = makeRestMovement(sourceVideoId, DEFAULT_REST_SEC, false);
      const rest: ReviewMovement = {
        id: `new_${Date.now()}`,
        workout_id: id ?? '',
        movement_id: movement.id,
        position: 0,
        movement,
        _key: `rest_${Date.now()}`,
      };
      const next = [...prev];
      next.splice(idx + 1, 0, rest);
      return next;
    });
  };

  // ON fills every gap between two moves that doesn't already have a rest,
  // marking those rows auto_generated. OFF removes only auto_generated rows
  // — a rest inserted by hand is never touched.
  const toggleRestBetweenMoves = (next: boolean) => {
    setRestOn(next);
    if (!next) {
      setMovements((prev) => prev.filter((m) => !m.movement.auto_generated));
      return;
    }
    setMovements((prev) => {
      const filled: ReviewMovement[] = [];
      prev.forEach((m, i) => {
        filled.push(m);
        const nextM = prev[i + 1];
        if (!m.movement.is_rest && nextM && !nextM.movement.is_rest) {
          const movement = makeRestMovement(sourceVideoId, DEFAULT_REST_SEC, true);
          filled.push({
            id: `new_${Date.now()}_${i}`,
            workout_id: id ?? '',
            movement_id: movement.id,
            position: 0,
            movement,
            _key: `rest_${Date.now()}_${i}`,
          });
        }
      });
      return filled;
    });
  };

  const deleteMovement = (key: string) => {
    const m = movements.find((m) => m._key === key);
    confirm('Remove movement?', m?.movement.name ?? '', 'Remove', () =>
      setMovements((prev) => prev.filter((m) => m._key !== key))
    );
  };

  const deleteWorkoutRow = async () => {
    if (!id) return;
    if (!(USE_MOCK && id === MOCK_WORKOUT.id)) {
      await supabase.from('workout_movements').delete().eq('workout_id', id);
      await supabase.from('workouts').delete().eq('id', id);
    }
    router.replace('/(tabs)/library');
  };

  const discardAndLeave = () => {
    if (isNew === 'true') {
      confirm('Discard workout?', 'This workout will not be saved.', 'Discard', deleteWorkoutRow);
    } else {
      router.back();
    }
  };

  const deleteWorkout = () => {
    confirm('Delete workout?', `"${title}" will be permanently removed.`, 'Delete', deleteWorkoutRow);
  };

  const saveEdits = async () => {
    if (!id) return;
    if (USE_MOCK && id === MOCK_WORKOUT.id) return;
    await supabase.from('workouts').update({ title }).eq('id', id);

    // Delete any removed workout_movements (only ones with real DB ids)
    const activeIds = new Set(movements.filter((m) => !m.id.startsWith('new_')).map((m) => m.id));
    const { data: existing } = await supabase.from('workout_movements').select('id').eq('workout_id', id);
    const toDelete = (existing ?? []).filter((r) => !activeIds.has(r.id)).map((r) => r.id);
    if (toDelete.length > 0) await supabase.from('workout_movements').delete().in('id', toDelete);

    // Everything below is batched into a handful of bulk calls instead of
    // looping per row — a flattened reps×sets workout easily runs 50-200+
    // rows, which meant that many serialized round trips on every Save.

    // Insert every brand-new movement row (e.g. a hand-inserted rest) in one
    // batch, then map each one's temp client-side id to the real id Postgres
    // assigns — a single multi-row INSERT...RETURNING preserves input order.
    const newMovements = movements
      .map((m, position) => ({ m, position }))
      .filter(({ m }) => m.movement.id.startsWith('new_movement_'));
    const movementIdMap = new Map<string, string>();
    if (newMovements.length > 0) {
      const { data: inserted } = await supabase.from('movements').insert(
        newMovements.map(({ m, position }) => ({
          source_video_id: m.movement.source_video_id,
          position,
          name: m.movement.name,
          mode: m.movement.mode,
          start_sec: m.movement.start_sec,
          end_sec: m.movement.end_sec,
          duration_sec: m.movement.duration_sec,
          reps: m.movement.reps,
          sets: m.movement.sets,
          clip_url: m.movement.clip_url,
          thumbnail_url: m.movement.thumbnail_url,
          detection_method: m.movement.detection_method,
          confidence: m.movement.confidence,
          is_rest: m.movement.is_rest,
          auto_generated: m.movement.auto_generated,
        }))
      ).select('id');
      (inserted ?? []).forEach((row, i) => movementIdMap.set(newMovements[i].m.movement.id, row.id));
    }

    // Bulk-update the rest. Postgres validates NOT NULL columns against the
    // row it would insert *before* checking for a conflict, even though
    // every one of these rows already exists and is headed for the UPDATE
    // branch — so every NOT NULL column has to be supplied here, not just
    // the two (name, duration_sec) that can actually change.
    const existingMovements = movements.filter((m) => !m.movement.id.startsWith('new_movement_'));
    if (existingMovements.length > 0) {
      await supabase.from('movements').upsert(
        existingMovements.map((m) => ({
          id: m.movement.id,
          source_video_id: m.movement.source_video_id,
          position: m.movement.position,
          name: m.movement.name,
          mode: m.movement.mode,
          duration_sec: m.movement.duration_sec,
          reps: m.movement.reps,
          sets: m.movement.sets,
          clip_url: m.movement.clip_url,
          thumbnail_url: m.movement.thumbnail_url,
          detection_method: m.movement.detection_method,
          confidence: m.movement.confidence,
          is_rest: m.movement.is_rest,
          auto_generated: m.movement.auto_generated,
        }))
      );
    }

    const resolvedMovementId = (m: ReviewMovement) => movementIdMap.get(m.movement.id) ?? m.movement.id;

    const wmToInsert = movements.map((m, position) => ({ m, position })).filter(({ m }) => m.id.startsWith('new_'));
    const wmToUpdate = movements.map((m, position) => ({ m, position })).filter(({ m }) => !m.id.startsWith('new_'));

    // workout_movements has a unique(workout_id, position) constraint, so
    // reordering (or inserting a new row in the middle, which shifts
    // everything after it) can ask to move a row into a slot another row
    // in this same save hasn't vacated yet — Postgres checks the
    // constraint immediately per row, not once at the end of the
    // statement, so that fails outright. Parking every existing row at a
    // temporary, guaranteed-clear position first sidesteps that: nothing
    // real occupies the target range by the time inserts/final positions
    // happen.
    if (wmToUpdate.length > 0) {
      await supabase.from('workout_movements').upsert(
        wmToUpdate.map(({ m }, i) => ({
          id: m.id,
          workout_id: id,
          movement_id: resolvedMovementId(m),
          position: 1_000_000 + i,
        }))
      );
    }

    if (wmToInsert.length > 0) {
      await supabase.from('workout_movements').insert(
        wmToInsert.map(({ m, position }) => ({
          workout_id: id,
          movement_id: resolvedMovementId(m),
          position,
        }))
      );
    }

    if (wmToUpdate.length > 0) {
      await supabase.from('workout_movements').upsert(
        wmToUpdate.map(({ m, position }) => ({
          id: m.id,
          workout_id: id,
          movement_id: resolvedMovementId(m),
          position,
        }))
      );
    }
  };

  const saveAndGoTo = async (destination: Href) => {
    setSaving(true);
    try {
      await saveEdits();
      router.replace(destination);
    } catch {
      notify('Save failed', 'Something went wrong. Try again.');
    } finally {
      setSaving(false);
    }
  };

  const saveToLibrary = () => { saveAndGoTo('/(tabs)/library'); };
  const save = () => { if (id) saveAndGoTo(`/workout/${id}`); };

  const makeWebPanResponder = (key: string) => {
    const cached = webPanResponders.current.get(key);
    if (cached) return cached;

    const responder = PanResponder.create({
      onStartShouldSetPanResponder: () => true,
      onMoveShouldSetPanResponder: (_: GestureResponderEvent, g: PanResponderGestureState) =>
        Math.abs(g.dy) > 4,
      onPanResponderGrant: () => {
        webDragStartIndex.current = movementsRef.current.findIndex((m) => m._key === key);
        setWebDragKey(key);
        setWebDragY(0);
      },
      onPanResponderMove: (_: GestureResponderEvent, g: PanResponderGestureState) => {
        setWebDragY(g.dy);
        const shift = Math.round(g.dy / webRowPitch.current);
        const targetIndex = Math.min(
          Math.max(webDragStartIndex.current + shift, 0),
          movementsRef.current.length - 1
        );
        setMovements((prev) => {
          const idx = prev.findIndex((m) => m._key === key);
          if (idx === -1 || idx === targetIndex) return prev;
          const next = [...prev];
          const [moved] = next.splice(idx, 1);
          next.splice(targetIndex, 0, moved);
          return next;
        });
      },
      onPanResponderRelease: () => {
        setWebDragKey(null);
        setWebDragY(0);
      },
      onPanResponderTerminate: () => {
        setWebDragKey(null);
        setWebDragY(0);
      },
    });
    webPanResponders.current.set(key, responder);
    return responder;
  };

  const renderCard = (m: ReviewMovement, isActive: boolean, reorderControl: React.ReactNode) => (
    <View style={[styles.card, m.movement.is_rest && styles.cardRest, isActive && styles.cardActive]}>
      {m.movement.is_rest ? (
        <View style={styles.thumb} />
      ) : m.movement.thumbnail_url ? (
        <Image source={{ uri: m.movement.thumbnail_url }} style={styles.thumb} />
      ) : (
        <View style={[styles.thumb, styles.thumbPlaceholder]} />
      )}
      <View style={styles.cardBody}>
        <TouchableOpacity
          onPress={() =>
            openEdit({ type: 'movement-name', key: m._key, movementId: m.movement.id, current: m.movement.name })
          }
        >
          <Text style={[styles.movementName, m.movement.is_rest && styles.movementNameRest]}>
            {m.movement.name}
          </Text>
        </TouchableOpacity>
        <TouchableOpacity
          onPress={() =>
            openEdit({ type: 'movement-duration', key: m._key, movementId: m.movement.id, current: String(m.movement.duration_sec ?? '') })
          }
        >
          <Text style={styles.movementDuration}>
            {m.movement.duration_sec != null ? `${m.movement.duration_sec}s` : '—'}
          </Text>
        </TouchableOpacity>
      </View>
      <View style={styles.cardActions}>
        <TouchableOpacity onPress={() => duplicate(m._key)} style={styles.actionBtn}>
          <Text style={styles.actionIcon}>⧉</Text>
        </TouchableOpacity>
        {!m.movement.is_rest && (
          <TouchableOpacity onPress={() => insertRestAfter(m._key)} style={styles.actionBtn}>
            <Text style={styles.actionIcon}>+☐</Text>
          </TouchableOpacity>
        )}
        <TouchableOpacity onPress={() => deleteMovement(m._key)} style={styles.actionBtn}>
          <Text style={[styles.actionIcon, styles.deleteIcon]}>✕</Text>
        </TouchableOpacity>
        {reorderControl}
      </View>
    </View>
  );

  const renderItem = ({ item: m, drag, isActive }: RenderItemParams<ReviewMovement>) => (
    <ScaleDecorator>
      {renderCard(
        m,
        isActive,
        <TouchableOpacity onLongPress={drag} delayLongPress={150} style={styles.actionBtn}>
          <Text style={styles.dragHandle}>⠿</Text>
        </TouchableOpacity>
      )}
    </ScaleDecorator>
  );

  const renderWebItem = ({ item: m }: ListRenderItemInfo<ReviewMovement>) => {
    const isDragging = webDragKey === m._key;
    const panResponder = makeWebPanResponder(m._key);
    return (
      <View
        onLayout={(e) => { webRowPitch.current = e.nativeEvent.layout.height + styles.list.gap; }}
        style={[
          isDragging && { transform: [{ translateY: webDragY }], zIndex: 10 },
        ]}
      >
        {renderCard(
          m,
          isDragging,
          <View {...panResponder.panHandlers} style={styles.actionBtn}>
            <Text style={styles.dragHandle}>⠿</Text>
          </View>
        )}
      </View>
    );
  };

  const listFooter = (
    <View>
      <View style={styles.footerBtns}>
        <TouchableOpacity style={styles.footerBtnSecondary} onPress={saveToLibrary} disabled={saving}>
          <Text style={styles.footerBtnSecondaryText}>{saving ? 'Saving…' : 'Save'}</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.footerBtnPrimary} onPress={save} disabled={saving}>
          <Text style={styles.footerBtnPrimaryText}>{saving ? 'Saving…' : 'Start'}</Text>
        </TouchableOpacity>
      </View>
      <TouchableOpacity style={styles.deleteWorkoutBtn} onPress={deleteWorkout}>
        <Text style={styles.deleteWorkoutText}>Delete Workout</Text>
      </TouchableOpacity>
    </View>
  );

  if (loading) {
    return (
      <SafeAreaView style={styles.safe}>
        <View style={styles.center}>
          <Text style={styles.muted}>Loading…</Text>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <SafeAreaView style={styles.safe}>
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity onPress={discardAndLeave}>
            <Text style={styles.cancelBtn}>Cancel</Text>
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Edit Workout</Text>
          <TouchableOpacity onPress={saveToLibrary} disabled={saving}>
            <Text style={[styles.saveBtn, saving && styles.saveBtnDim]}>{saving ? '…' : 'Save'}</Text>
          </TouchableOpacity>
        </View>

        {/* Workout title */}
        <TouchableOpacity
          style={styles.titleRow}
          onPress={() => openEdit({ type: 'title', key: 'title', current: title })}
        >
          <Text style={styles.workoutTitle}>{title}</Text>
          <Text style={styles.editHint}>tap to rename</Text>
        </TouchableOpacity>

        <View style={styles.sectionRow}>
          <View style={styles.sectionMeta}>
            <Text style={styles.sectionLabel}>{movements.length} movements</Text>
            <Text style={styles.sectionHint}>{IS_WEB ? 'Drag ⠿ to reorder' : 'Hold ⠿ to reorder'}</Text>
          </View>
        </View>

        <View style={styles.restToggleRow}>
          <View style={{ flex: 1 }}>
            <Text style={styles.restToggleLabel}>Rest between moves</Text>
            <Text style={styles.restToggleHint}>Fills gaps · only touches auto rests</Text>
          </View>
          <Switch
            value={restOn}
            onValueChange={toggleRestBetweenMoves}
            trackColor={{ false: Colors.border, true: Colors.accentDim }}
            thumbColor={Colors.accent}
          />
        </View>

        <View style={styles.bulkRow}>
          <TouchableOpacity
            onPress={() => openEdit({ type: 'all-move-durations', key: 'all-move', current: '' })}
            style={[styles.setAllBtnWrap, styles.setAllBtnMove]}
          >
            <Text style={styles.setAllBtn}>Set all move durations</Text>
          </TouchableOpacity>
          <TouchableOpacity
            onPress={() => openEdit({ type: 'all-rest-durations', key: 'all-rest', current: '' })}
            style={[styles.setAllBtnWrap, styles.setAllBtnRest]}
          >
            <Text style={[styles.setAllBtn, styles.setAllBtnTextRest]}>Set all rest durations</Text>
          </TouchableOpacity>
        </View>

        {IS_WEB ? (
          <FlatList
            data={movements}
            keyExtractor={(m) => m._key}
            renderItem={renderWebItem}
            contentContainerStyle={styles.list}
            ListFooterComponent={listFooter}
          />
        ) : (
          <DraggableFlatList
            data={movements}
            keyExtractor={(m) => m._key}
            onDragEnd={({ data }) => setMovements(data)}
            renderItem={renderItem}
            contentContainerStyle={styles.list}
            ListFooterComponent={listFooter}
          />
        )}

        {/* Inline edit modal */}
        <Modal visible={!!editTarget} transparent animationType="fade">
          <KeyboardAvoidingView
            behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
            style={styles.modalOverlay}
          >
            <TouchableOpacity style={StyleSheet.absoluteFill} onPress={() => setEditTarget(null)} />
            <View style={styles.modalCard}>
              <Text style={styles.modalLabel}>
                {editTarget?.type === 'title'
                  ? 'Workout name'
                  : editTarget?.type === 'movement-name'
                  ? 'Movement name'
                  : editTarget?.type === 'all-move-durations'
                  ? 'Set all move durations (seconds)'
                  : editTarget?.type === 'all-rest-durations'
                  ? 'Set all rest durations (seconds)'
                  : 'Duration (seconds)'}
              </Text>
              <TextInput
                style={styles.modalInput}
                value={editValue}
                onChangeText={setEditValue}
                keyboardType={
                  editTarget?.type === 'movement-duration' ||
                  editTarget?.type === 'all-move-durations' ||
                  editTarget?.type === 'all-rest-durations'
                    ? 'number-pad'
                    : 'default'
                }
                autoFocus
                selectTextOnFocus
                returnKeyType="done"
                onSubmitEditing={commitEdit}
              />
              <View style={styles.modalActions}>
                <TouchableOpacity onPress={() => setEditTarget(null)} style={styles.modalCancel}>
                  <Text style={styles.modalCancelText}>Cancel</Text>
                </TouchableOpacity>
                <TouchableOpacity onPress={commitEdit} style={styles.modalConfirm}>
                  <Text style={styles.modalConfirmText}>Done</Text>
                </TouchableOpacity>
              </View>
            </View>
          </KeyboardAvoidingView>
        </Modal>
      </SafeAreaView>
    </GestureHandlerRootView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  muted: { color: Colors.textMuted, fontSize: 15 },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  cancelBtn: { color: Colors.textSecondary, fontSize: 15 },
  deleteWorkoutBtn: { marginTop: 12, paddingVertical: 14, alignItems: 'center' as const },
  deleteWorkoutText: { color: Colors.error, fontSize: 14, fontWeight: '600' as const },
  headerTitle: { color: Colors.text, fontSize: 15, fontWeight: '600' },
  saveBtn: { color: Colors.accent, fontSize: 15, fontWeight: '700' },
  saveBtnDim: { opacity: 0.5 },
  footerBtns: { flexDirection: 'row', gap: 10, marginTop: 24, paddingBottom: 8 },
  footerBtnPrimary: {
    flex: 1, height: 52, borderRadius: 14, backgroundColor: Colors.accent,
    alignItems: 'center', justifyContent: 'center',
  },
  footerBtnPrimaryText: { color: '#000', fontSize: 16, fontWeight: '800' },
  footerBtnSecondary: {
    flex: 1, height: 52, borderRadius: 14, borderWidth: 1.5, borderColor: Colors.border,
    alignItems: 'center', justifyContent: 'center',
  },
  footerBtnSecondaryText: { color: Colors.text, fontSize: 16, fontWeight: '600' },

  titleRow: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  workoutTitle: { color: Colors.text, fontSize: 22, fontWeight: '700', flex: 1 },
  editHint: { color: Colors.textMuted, fontSize: 12 },

  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 14,
  },
  sectionMeta: {
    gap: 3,
  },
  sectionLabel: {
    color: Colors.text,
    fontSize: 15,
    fontWeight: '700',
  },
  sectionHint: {
    color: Colors.textMuted,
    fontSize: 12,
  },
  restToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginHorizontal: 16,
    borderRadius: 12,
    backgroundColor: Colors.surfaceAlt,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  restToggleLabel: { color: Colors.text, fontSize: 14, fontWeight: '600' },
  restToggleHint: { color: Colors.textMuted, fontSize: 11, marginTop: 2 },

  bulkRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
  },
  setAllBtnWrap: {
    flex: 1,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: 'center',
  },
  setAllBtnMove: { borderColor: Colors.accentDim },
  setAllBtnRest: { borderColor: Colors.textMuted, borderStyle: 'dashed' },
  setAllBtn: {
    color: Colors.accent,
    fontSize: 12.5,
    fontWeight: '600',
  },
  setAllBtnTextRest: { color: Colors.textSecondary },

  list: { paddingHorizontal: 16, gap: 8, paddingBottom: 40 },

  card: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  cardActive: {
    borderColor: Colors.accent,
    shadowColor: Colors.accent,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  cardRest: { backgroundColor: 'transparent', borderStyle: 'dashed', borderColor: Colors.textMuted },
  thumb: { width: 72, height: 72 },
  thumbPlaceholder: { backgroundColor: Colors.surfaceAlt },
  cardBody: { flex: 1, gap: 4, paddingHorizontal: 12, paddingVertical: 12 },
  movementName: { color: Colors.text, fontSize: 15, fontWeight: '600' },
  movementNameRest: { color: Colors.textSecondary },
  movementDuration: { color: Colors.textSecondary, fontSize: 13 },

  cardActions: { flexDirection: 'column', alignItems: 'center', paddingRight: 4 },
  actionBtn: { padding: 7 },
  actionIcon: { color: Colors.textSecondary, fontSize: 15 },
  deleteIcon: { color: Colors.error },
  dragHandle: { color: Colors.textMuted, fontSize: 18 },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    gap: 16,
  },
  modalLabel: { color: Colors.textSecondary, fontSize: 13, fontWeight: '600' },
  modalInput: {
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: Colors.text,
    fontSize: 16,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  modalActions: { flexDirection: 'row', gap: 10 },
  modalCancel: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  modalCancelText: { color: Colors.textSecondary, fontSize: 15 },
  modalConfirm: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: Colors.accent,
  },
  modalConfirmText: { color: '#000', fontSize: 15, fontWeight: '700' },
});
